version: '2.4'
services:

  # The Application
  app:
    image: ghcr.io/futureecom/php-app-web:dev-3.3.3

    volumes:
    - ./:/var/www/html
    networks:
      - backend
      - frontend
    ports:
      - 8080:8080
    environment:
      - VIRTUAL_HOST=futureecom.platform
      - PHP_FPM_PM=dynamic
      - PHP_FPM_MAX_CHILDREN=40
      - PHP_FPM_START_SERVERS=8
      - PHP_FPM_MIN_SPARE_SERVERS=4
      - PHP_FPM_MAX_SPARE_SERVERS=8
      - PHP_FPM_MAX_REQUESTS=200
      - PHP_FPM_IDLE_TIMEOUT=10s

  # The Database
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./storage/mongodb:/data/db
    networks:
      - backend

  # Redis
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - backend

  # Websocket
  websocket:
    image: futureecom/websocket:0.0.15
    # hostname: futureecom.socket //required only if SERVER_ADDRESS environment will be used
    ports:
      - 8001:8080
    networks:
      - backend
      - frontend
    environment:
      # AUTH_PUBLIC_KEY: "secret\n" //replace with your key used for JWT encode
      # SERVER_ADDRESS: "futureecom.socket:8080" // not mandatory, defaults to localhost
      REDIS_HOST: redis
      ALLOWED_ORIGINS: "*"

networks:
  backend:
    driver: bridge
  frontend:
    name: discovery
    external: true
